# Generated by Django 5.1.3 on 2024-11-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_address_line_1_alter_profile_county_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='postalcode',
            new_name='post_code',
        ),
    ]
