# Generated by Django 5.1.3 on 2024-11-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_postalcode_profile_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_comms_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
