# Generated by Django 5.1.3 on 2024-11-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default_images/default_profile.jpg', upload_to='profile_pics'),
        ),
    ]
