# Generated by Django 5.1.3 on 2024-11-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(auto_created=True, max_length=30, null=True, unique=True),
        ),
    ]
