# Generated by Django 5.1.3 on 2024-11-15 09:37

from django.db import migrations
from django.utils.text import slugify
import uuid


def generate_unique_slugs(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    for profile in Profile.objects.all():
        # Generate a unique slug
        profile.slug = slugify(str(uuid.uuid4()))
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_slug'),
    ]

    operations = [
        migrations.RunPython(generate_unique_slugs),
    ]
