# Generated by Django 5.1.3 on 2024-11-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
    ]
