# Generated by Django 5.1.3 on 2024-11-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_profile_interests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
