# Generated by Django 5.1.3 on 2024-11-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_groups_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='description',
            field=models.TextField(default='null', max_length=1500),
            preserve_default=False,
        ),
    ]
