# Generated by Django 5.1.3 on 2024-11-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groups_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='image',
            field=models.ImageField(blank=True, default='default_group_pic.png', upload_to='group_pics'),
        ),
    ]
