# Generated by Django 5.1.3 on 2024-11-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_rename_events_event_rename_groups_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, default='group_pics/default_group_pic.png', upload_to='group_pics'),
        ),
    ]
