# Generated by Django 5.1.3 on 2024-11-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_group_image'),
        ('users', '0018_remove_profile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='default_event_pic.png', upload_to='event_pics'),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, default='default_group_pic.png', upload_to='group_pics'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='groups', to='users.profile'),
        ),
    ]
