# Generated by Django 5.1.3 on 2024-11-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_event_image_alter_group_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='attendants',
            new_name='attendees',
        ),
    ]
